when:
  - event: push
    branch: main
  - event: pull_request

matrix:
  include:
    - platform: linux/amd64
      image: harbor.vdx.hu/voidcontext/woodpecker-plugin-nix-attic:0.3.0-alpha7
    - platform: linux/arm64
      image: harbor.vdx.hu/voidcontext/aarch64/woodpecker-plugin-nix-attic:0.3.0-alpha7

labels:
  platform: ${platform}

steps:
  check:
    image: ${image}
    settings:
      binary_cache: https://cache.nix.vdx.hu/private
      binary_cache_public_key: private:O0/Z0BQZpKKHQQES65u7xNfZF7eCZoz9RKJi191TGaM=
      binary_cache_token:
        from_secret: attic_token
      script: |
        nix flake check

        attic login attic $PLUGIN_BINARY_CACHE $PLUGIN_BINARY_CACHE_TOKEN
        attic push private $(nix-store --query --requisites --include-outputs $(nix path-info --derivation .#default))
